### ISSUE TITLE
FlagWar not working properly due to some errors

### ISSUE THREAD

**Issue by MetalWarLord** [TownyAdvanced/FlagWar#100]
### What steps will reproduce the problem?
1. Start a Flag War
2. Not placing light block and hologram
3. The flag's color does not change and the war does not end even if the waiting time is elapsed
4. Breaking the flag triggers the end and the defended message is shown
5. New flag war can not be started due to a NullPointerException

### What is the expected output?
1. Flag War starting and the attacker wins if the conditions are met
2. Changing colors and showing holograms
3. Attackers can start another war after the first one ended

### What is your Towny version number?
0.97.2.0

### What is your FlagWar version number?
0.5.1

### What is your Spigot/Paper/Fork server version?
Paper 1.16.5

```
> version
[19:52:19 INFO]: Checking version, please wait...
[19:52:20 WARN]: java.io.FileNotFoundException: https://papermc.io/api/v1/paper/1.16.5/latest
[19:52:20 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1981)
[19:52:20 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[19:52:20 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[19:52:20 WARN]:        at java.base/java.net.URL.openStream(URL.java:1192)
[19:52:20 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[19:52:20 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
[19:52:20 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
[19:52:20 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.fetchDistanceFromSiteApi(PaperVersionFetcher.java:82)
[19:52:20 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.getUpdateStatusMessage(PaperVersionFetcher.java:58)
[19:52:20 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.getVersionMessage(PaperVersionFetcher.java:32)
[19:52:20 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:205)
[19:52:20 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$000(VersionCommand.java:30)
[19:52:20 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:189)
[19:52:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[19:52:20 INFO]: This server is running Paper version git-Paper-706 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Paper-189 (MC: 1.16.2)
```

### Please use a pastebin service to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly.
If you do skip this step then your ticket will most likely be deleted, and you will be asked to resubmit.**
1. latest.log : https://pastebin.com/4HKmPn03
2. FlagWar config : https://pastebin.com/H4s5eA2n
3. Log's error (on breaking the flag by a defender): https://pastebin.com/k45pr1Fd
4. Log's error (on trying to start another war): https://pastebin.com/NVJEP5xi
5. Towny config (if needed): https://pastebin.com/ZjybSZ8Y

**Comment by LlmDl** [comment]
I'm not able to look into this in depth right now but both Towny and FlagWar are out of date. It might be worth updating and checking if the error is still present.

**Comment by MetalWarLord** [comment]
I've tried it with the newest versions and still getting these errors.

**Comment by LlmDl** [comment]
Can you supply the new errors?

**Comment by MetalWarLord** [comment]
I've got the same errors when I tried it with the newest versions.
The other server owner tested it later and said that if you turn on the beacon this problem will not occur, but I didn't have time to test this properly.
