### ISSUE TITLE
FlagWar-0.1.0.jar does not start

### ISSUE THREAD

**Issue by Darutan92** [TownyAdvanced/FlagWar#13]
### What steps will reproduce the problem?
1. Download and put into plugin Towny-0.96.7.3
2. Download and put into plugin FlagWar-0.1.0
3. Start the server on PaperSpigot 1.16.5 - paper-1.16.5-509.jar

```
[16:02:55 ERROR]: Could not load 'plugins\FlagWar-0.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-509]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: java.lang.ExceptionInInitializerError
	at io.github.townyadvanced.flagwar.FlagWar.<init>(FlagWar.java:77) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-509]
	... 7 more
Caused by: java.lang.NullPointerException
	at com.palmergames.bukkit.towny.object.Translation.of(Translation.java:70) ~[?:?]
	at io.github.townyadvanced.flagwar.listeners.FlagWarCustomListener.<clinit>(FlagWarCustomListener.java:59) ~[?:?]
	at io.github.townyadvanced.flagwar.FlagWar.<init>(FlagWar.java:77) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_271]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-509]
	... 7 more
```
The same thing happens on the YaTopia core and with Tovny 0.96.7.4.

**Comment by TheFlagCourier** [comment]
Thanks for reporting this in! This should actually be fixed in the next pre-release. If you'd like to try it early, you can build against #11. Otherwise, should have it out sometime this week.

**Comment by Darutan92** [comment]
Hello. Ok, I'll wait for the new version. Hopefully, Flag War will eventually become a full-fledged war system, with all the additions, customizability and fixes it needs.
