### ISSUE TITLE
The plot does not change after the time has passed

### ISSUE THREAD

**Issue by BallkingCN** [TownyAdvanced/FlagWar#336]
### What steps will reproduce the problem?
1.use 1.20.1 folia-kaiijiu
2.use towny 0.100.1.0
3.use Flagwar 0.6.2

### What is the expected output?
1.the timer block dosesnt change its block
2.the plot dosen't change when the time has ended(the attacker win the fight)
3.the plot change on the first time i use.but it error in a flght at night.

### What is your Towny version number?
0.100.1.0

### What is your FlagWar version number?
use Flagwar 0.6.2

### What is your Spigot/Paper/Fork server version?
1.20.1 folia-kaiijiu

```shell
## THIS IS AN EXAMPLE! REPLACE ME!
> version
the log is too big(6.8g)so i cant open the report
```

### Please use a pastebin service to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly.
If you do skip this step then your ticket will most likely be deleted, and you will be asked to resubmit.**
1. Your full server startup from the `logs\latest.log` file :
[2024-01-16-5.zip](https://github.com/TownyAdvanced/FlagWar/files/13958805/2024-01-16-5.zip)

2. Your FlagWar config :
[config.zip](https://github.com/TownyAdvanced/FlagWar/files/13958760/config.zip)

3. Your log's error :
the log doesnt has change when it happen
(optional) If this is to do with permissions,
4. Your Towny permissions file :
[townyperms.zip](https://github.com/TownyAdvanced/FlagWar/files/13958776/townyperms.zip)

5. Your Perm Plugin's data :

**Comment by LlmDl** [comment]
I just had this working on my test server that runs on Paper with a near-identical configuration.

**Comment by LlmDl** [comment]
Actually I have re-read your explanation of what you want to have happen and I do not understand your translations.


What problem are you seeing?

What steps do you use to get the problem?

In detail explain what is not happening, which you expect to have happen.

**Comment by shishioko** [comment]
I am experiencing the same issue.
This issue only seems to occur on server running the Folia server software.
While the mentioned events occur, a error along the lines of "cell won even may only be triggered synchronously towny flagwar" is periodically thrown in the console.

**Comment by shishioko** [comment]
It is still throwing errors, using the updated .jar. Here are the errors thrown after trying to conquer a townyblock:

[01:19:20 ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread failed main thread check: Cannot read world asynchronously, context=[thread=Thread[#81,Folia Async Scheduler Thread #2,4,main],class=java.lang.Thread], world=earth, block_pos=BlockPos{x=4969, y=65, z=-1542}
java.lang.Throwable: null
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:61) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.getNMS(CraftBlock.java:80) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.setBlockState(CraftBlock.java:205) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.setBlockData(CraftBlock.java:201) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.setType(CraftBlock.java:190) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.setType(CraftBlock.java:184) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at FlagWar-0.7.1.jar/io.github.townyadvanced.flagwar.objects.CellUnderAttack.updateFlag(CellUnderAttack.java:255) ~[FlagWar-0.7.1.jar:?]
        at FlagWar-0.7.1.jar/io.github.townyadvanced.flagwar.objects.CellUnderAttack.changeFlag(CellUnderAttack.java:228) ~[FlagWar-0.7.1.jar:?]
        at FlagWar-0.7.1.jar/io.github.townyadvanced.flagwar.CellAttackThread.run(CellAttackThread.java:47) ~[FlagWar-0.7.1.jar:?]
        at FlagWar-0.7.1.jar/io.github.townyadvanced.flagwar.objects.CellUnderAttack.lambda$beginAttack$1(CellUnderAttack.java:369) ~[FlagWar-0.7.1.jar:?]
        at Towny-0.101.2.0.jar/com.palmergames.bukkit.towny.scheduling.TaskScheduler.lambda$runRepeating$6(TaskScheduler.java:102) ~[Towny-0.101.2.0.jar:?]
        at Towny-0.101.2.0.jar/com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambda$runAsyncRepeating$8(FoliaTaskScheduler.java:145) ~[Towny-0.101.2.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.21.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:19:20 WARN]: [FlagWar] Async task for FlagWar v0.7.1 generated an exception
java.lang.IllegalStateException: Thread failed main thread check: Cannot read world asynchronously, context=[thread=Thread[#81,Folia Async Scheduler Thread #2,4,main],class=java.lang.Thread], world=earth, block_pos=BlockPos{x=4969, y=65, z=-1542}
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:62) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.getNMS(CraftBlock.java:80) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.setBlockState(CraftBlock.java:205) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.setBlockData(CraftBlock.java:201) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.setType(CraftBlock.java:190) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at org.bukkit.craftbukkit.block.CraftBlock.setType(CraftBlock.java:184) ~[folia-1.21.6.jar:1.21.6-6-e4b0ae9]
        at FlagWar-0.7.1.jar/io.github.townyadvanced.flagwar.objects.CellUnderAttack.updateFlag(CellUnderAttack.java:255) ~[FlagWar-0.7.1.jar:?]
        at FlagWar-0.7.1.jar/io.github.townyadvanced.flagwar.objects.CellUnderAttack.changeFlag(CellUnderAttack.java:228) ~[FlagWar-0.7.1.jar:?]
        at FlagWar-0.7.1.jar/io.github.townyadvanced.flagwar.CellAttackThread.run(CellAttackThread.java:47) ~[FlagWar-0.7.1.jar:?]
        at FlagWar-0.7.1.jar/io.github.townyadvanced.flagwar.objects.CellUnderAttack.lambda$beginAttack$1(CellUnderAttack.java:369) ~[FlagWar-0.7.1.jar:?]
        at Towny-0.101.2.0.jar/com.palmergames.bukkit.towny.scheduling.TaskScheduler.lambda$runRepeating$6(TaskScheduler.java:102) ~[Towny-0.101.2.0.jar:?]
        at Towny-0.101.2.0.jar/com.palmergames.bukkit.towny.scheduling.impl.FoliaTaskScheduler.lambda$runAsyncRepeating$8(FoliaTaskScheduler.java:145) ~[Towny-0.101.2.0.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.21.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by LlmDl** [comment]
FlagWar doesn't appear to run that task async so I'm not sure how it manages to get you that error:

```java
    public void beginAttack() {
        drawFlag();
        final int tps = 20;
        final int milliTicks = 50;
        final long ticksFromMs = this.flagPhaseDuration.toMillis() / milliTicks;
        threadTask = scheduler.runRepeating(() -> thread.run(), ticksFromMs, ticksFromMs);   <==== thread.run() is line 369 see in your Error above.
        if (FlagWarConfig.isHologramEnabled()) {
            drawHologram();
            if (FlagWarConfig.hasTimerLine()) {
                hologramTask = scheduler.runRepeating(() -> hologramThread.run(), tps, tps);
            }
        }
    }
```

**Comment by LlmDl** [comment]
Are you using Luminol?
