### ISSUE TITLE
Plugin does not start

### ISSUE THREAD

**Issue by likel0vsky** [TownyAdvanced/FlagWar#77]
Hello
I have installed the Towny plugin and FlagWars to Paper 1.16.5 server, but I saw an error in server console:

```
[ERROR] .... Could not load 'plugins/FlagWar-0.4.0.jar' in folder 'plugins'

org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: io/github/townyadvanced/flagwar/FlagWar has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-778]

at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-778]

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-778]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-778]

at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-778]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-778]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Caused by: java.lang.UnsupportedClassVersionError: io/github/townyadvanced/flagwar/FlagWar has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]

at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]

at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Paper-778]

at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-778]

at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-778]

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]

at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]

at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-778]

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-778]
```

What can I do to fix this problem?

**Comment by LlmDl** [comment]
Looks like you probably need to install Java16

**Comment by likel0vsky** [comment]
I've installed Java 16 and it's working. Thank you!
